vich_uploader:
    db_driver: orm

    mappings:
        users_img:
            uri_prefix: /images/utilisateurs
            upload_destination: '%kernel.project_dir%/public/images/utilisateurs'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
